### ISSUE TITLE
downloads' page does not work normally.

### ISSUE THREAD

**Issue by hebin123456** [yongshengli/yiicms#1]
I have tested this system then I found the page 'downloads' does not work normally.If I want to modify some data, it works normally, but when I want to add something, It can't do, can you fix this bug? thank you.

**Comment by hebin123456** [comment]
下载页面不正常，想修改里面的数据是可以修改的，但是如果想要添加数据的话就会添加失败，可以修复这个bug吗，谢谢

**Comment by yongshengli** [comment]
已解决 https://github.com/yongshengli/yiicms/commit/acd81b163bab5187cee1bd0274a5901ac7f6418a
