### ISSUE TITLE
Information disclosure leads to privilege escalation

### ISSUE THREAD

**Issue by Huuuz** [yongshengli/yiicms#5]
General administrative account (demo), it can obtain the super administrator password through the disclosure of password modification information.
Additional information：
Demo does not have permission to change the password of admin
![image](https://user-images.githubusercontent.com/40735222/66621922-6d61b180-ec18-11e9-9065-d0a27571301d.png)
But html leaked admin's password hash.
![image](https://user-images.githubusercontent.com/40735222/66621893-4d31f280-ec18-11e9-9732-fb9b66754be6.png)
Successfully logged in to admin through md5 decryption
![image](https://user-images.githubusercontent.com/40735222/66622107-21633c80-ec19-11e9-8ad5-3b2c02b1b2f7.png)

**Comment by yongshengli** [comment]
好的，收到，多谢

**Comment by yongshengli** [comment]
https://github.com/yongshengli/yiicms/blob/4a9d68564eb78d9f64e3f5dd77186a154093615b/modules/backend/views/admin-user/_form.php#L17
